# Generated by Django 4.2.17 on 2026-02-04 13:55

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Category',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('name', models.CharField(help_text='Category name', max_length=100, unique=True)),
                ('color', models.CharField(help_text='Hex color code (e.g., #FF5733)', max_length=7)),
                ('sort_order', models.IntegerField(default=0, help_text='Display order (lower values appear first)')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Category',
                'verbose_name_plural': 'Categories',
                'ordering': ['sort_order', 'name'],
                'indexes': [models.Index(fields=['sort_order'], name='categories__sort_or_ac4749_idx')],
            },
        ),
    ]
