# Generated by Django 4.2.17 on 2026-02-04 14:08

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('categories', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Note',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('title', models.CharField(default='Note Title', help_text='Note title', max_length=500)),
                ('content', models.TextField(blank=True, default='', help_text='Note content/body')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('last_edited_at', models.DateTimeField(auto_now=True, help_text='Last time the note was edited')),
                ('category', models.ForeignKey(help_text='Category this note belongs to', on_delete=django.db.models.deletion.PROTECT, related_name='notes', to='categories.category')),
                ('user', models.ForeignKey(help_text='Owner of the note', on_delete=django.db.models.deletion.CASCADE, related_name='notes', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Note',
                'verbose_name_plural': 'Notes',
                'ordering': ['-last_edited_at'],
                'indexes': [models.Index(fields=['user', '-last_edited_at'], name='notes_note_user_id_3bed52_idx'), models.Index(fields=['category'], name='notes_note_categor_9978d8_idx'), models.Index(fields=['-last_edited_at'], name='notes_note_last_ed_2f0333_idx')],
            },
        ),
    ]
