# Generated by Django 4.2.17 on 2026-02-04 14:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('notes', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='note',
            name='title',
            field=models.CharField(default='Note Title:', help_text='Note title', max_length=500),
        ),
    ]
