# Generated by Django 4.2.17 on 2026-02-04 14:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('notes', '0002_alter_note_title'),
    ]

    operations = [
        migrations.AlterField(
            model_name='note',
            name='title',
            field=models.CharField(blank=True, default='Note Title:', help_text='Note title', max_length=500),
        ),
    ]
